version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      # Checkout the code from the branch into the working_directory-
      - checkout
      - run: npm install
      - run: npm test
