version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      # Checkout the code from the branch into the working_directory-
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}     
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules     
      - run: npm test
      - run: ssh -o StrictHostKeyChecking=no sulha199@github.com
      - run: npm run build
      - run: ng build --prod --base-href=https://sulha199.github.io/yang_paling
      - run: npx ngh --repo=https://github.com/sulha199/yang_paling.git --dir=dist --name=sulha199
