version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      # Checkout the code from the branch into the working_directory-
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "80:5b:4f:f9:fb:93:38:86:59:33:ab:5d:15:33:75:80"
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: sudo npm run deploy
