workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      # Checkout the code from the branch into the working_directory-
      - checkout:
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
      - run: npm run build --prod --base-href=https://sulha199.github.io/yang_paling/${CIRCLE_BRANCH}
      - save_cache: # special step to save the dist cache	
          key: dependency-cache-${CIRCLE_BRANCH}-${CIRCLE_SHA1}
          paths:
            - ~/repo/dist
      - run: ls
  deploy:
    docker:
      - image: circleci/node:10.16.3-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - restore_cache: # special step to restore the deploy cache
          key: dependency-cache-${CIRCLE_BRANCH}-${CIRCLE_SHA1}
      - add_ssh_keys:
          fingerprints:
            - "a5:a6:8b:1e:ff:a6:d5:f7:03:fa:75:a3:14:68:f4:d3"
      - run:
          name: Clone gh-pages branch
          working_directory: ~/repo/deploy
          command: |
            git clone --depth 1 -b gh-pages git@github.com:sulha199/yang_paling.git .
      - run: ls
      - run:
          name: delete folder with current branch name if exist
          command: rm -rf ~/repo/deploy/${CIRCLE_BRANCH}
      - run: mkdir ~/repo/deploy/${CIRCLE_BRANCH}
      - run:
          name: move build result to deploy folder with branch-name
          command: mv ./dist/* ~/repo/deploy/${CIRCLE_BRANCH} -i
      - run: cd ~/repo/deploy && ls
      - run: cd ~/repo/deploy/${CIRCLE_BRANCH} && ls
      - deploy:
          name: Trigger commit and push
          working_directory: ~/repo/deploy
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "sulha199@gmail.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "commited by CI"
            # Push quietly to prevent showing the token in log
            git push -q
